
cluster-sidecar: "slurm-sidecar.py"
cluster-cancel: "scancel"
restart-times: "0"
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
max-jobs-per-second: "500"
max-status-checks-per-second: "10"
local-cores: 2
latency-wait: "60"

use-conda: "True"
use-singularity: "True"
use-envmodules: True
notemp: True

keep-going: True
scheduler: "greedy"
jobs: "1500"
cores: 2500
printshellcmds: "False"

rerun-trigger: "mtime"
quiet: "rules" 

default-resources:
  - threads=1
  - mem_mb=1024
  - walltime="4h"
  - scratch="1G"
# Example resource configuration
# default-resources:
#   - runtime=100
#   - mem_mb=6000
#   - disk_mb=1000000
# # set-threads: map rule names to threads
# set-threads:
#   - single_core_rule=1
#   - multi_core_rule=10
# # set-resources: map rule names to resources in general
# set-resources:
#   - high_memory_rule:mem_mb=12000
#   - long_running_rule:runtime=1200
