cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --cpus-per-task={threads}
    --mem-per-cpu={resources.mem_mb}
    --time={resources.walltime}:00
    --tmp={resources.scratch}
    --job-name={rule}-{wildcards}
    --output=logs/{rule}/{wildcards}-$(date +%F-%T)-%j.out
    --error=logs/{rule}/{wildcards}-$(date +%F-%T)-%j.err
cluster-status: "status-scontrol.sh"
default-resources:
  - threads=1
  - mem_mb=1000
  - walltime="4:00"
  - scratch="1G"
restart-times: 0
max-jobs-per-second: 100
max-status-checks-per-second: 10
local-cores: 4
latency-wait: 60
jobs: 2000
cores: 2500
notemp: True
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
use-singularity: True
keep-going: True
use-envmodules: True
quiet: "rules"
rerun-trigger: "mtime"
